### ISSUE TITLE
pry gem required for installation?

### ISSUE THREAD

**Issue by mofahead** [KevinColemanInc/yeet_dba#11]
I had to install pry (maybe most users have this installed already?) to get this to work.

If this is a hard dependency, maybe include a note in the installation section of the README?

**Comment by KevinColemanInc** [comment]
I was just using it for development. I will remove it.

**Comment by KevinColemanInc** [comment]
Removed the gem here: https://github.com/KevinColemanInc/yeet_dba/pulls?q=is%3Apr+is%3Aclosed
